In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [5]:
data=pd.read_csv(r"C:\Users\Ravi\OneDrive\Desktop\ML Project\ML Linear Regression Home Price Prediction & Analysis Project Resource16932049360.txt")

In [6]:
data

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,03/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,03/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,04/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.80790,144.99340,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,04/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.81140,145.01160,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,04/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.80930,144.99440,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,13 Burns St,4,h,1480000.0,PI,Jas,24/02/2018,6.3,3013.0,...,1.0,3.0,593.0,NaN,NaN,Maribyrnong City Council,-37.81053,144.88467,Western Metropolitan,6543.0
34853,Yarraville,29A Murray St,2,h,888000.0,SP,Sweeney,24/02/2018,6.3,3013.0,...,2.0,1.0,98.0,104.0,2018.0,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0
34854,Yarraville,147A Severn St,2,t,705000.0,S,Jas,24/02/2018,6.3,3013.0,...,1.0,2.0,220.0,120.0,2000.0,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0
34855,Yarraville,12/37 Stephen St,3,h,1140000.0,SP,hockingstuart,24/02/2018,6.3,3013.0,...,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council,NaN,NaN,Western Metropolitan,6543.0
34856,Yarraville,3 Tarrengower St,2,h,1020000.0,PI,RW,24/02/2018,6.3,3013.0,...,1.0,0.0,250.0,103.0,1930.0,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0

In [8]:
data.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [10]:
data.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,34857.000000,2.724700e+04,34856.000000,34856.000000,26640.000000,26631.000000,26129.000000,23047.000000,13742.00000,15551.000000,26881.000000,26881.000000,34854.000000
mean,3.031012,1.050173e+06,11.184929,3116.062859,3.084647,1.624798,1.728845,593.598993,160.25640,1965.289885,-37.810634,145.001851,7572.888306
std,0.969933,6.414671e+05,6.788892,109.023903,0.980690,0.724212,1.010771,3398.841946,401.26706,37.328178,0.090279,0.120169,4428.090313
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1196.000000,-38.190430,144.423790,83.000000
25%,2.000000,6.350000e+05,6.400000,3051.000000,2.000000,1.000000,1.000000,224.000000,102.00000,1940.000000,-37.862950,144.933500,4385.000000
50%,3.000000,8.700000e+05,10.300000,3103.000000,3.000000,2.000000,2.000000,521.000000,136.00000,1970.000000,-37.807600,145.007800,6763.000000
75%,4.000000,1.295000e+06,14.000000,3156.000000,4.000000,2.000000,2.000000,670.000000,188.00000,2000.000000,-37.754100,145.071900,10412.000000
max,16.000000,1.120000e+07,48.100000,3978.000000,30.000000,12.000000,26.000000,433014.000000,44515.00000,2106.000000,-37.390200,145.526350,21650.000000

In [14]:
print(data.describe(include='all'))

           Suburb       Address         Rooms   Type         Price Method  \
count       34857         34857  34857.000000  34857  2.724700e+04  34857
unique        351         34009           NaN      3           NaN      9
top     Reservoir  5 Charles St           NaN      h           NaN      S
freq          844             6           NaN  23980           NaN  19744
mean          NaN           NaN      3.031012    NaN  1.050173e+06    NaN
std           NaN           NaN      0.969933    NaN  6.414671e+05    NaN
min           NaN           NaN      1.000000    NaN  8.500000e+04    NaN
25%           NaN           NaN      2.000000    NaN  6.350000e+05    NaN
50%           NaN           NaN      3.000000    NaN  8.700000e+05    NaN
75%           NaN           NaN      4.000000    NaN  1.295000e+06    NaN
max           NaN           NaN     16.000000    NaN  1.120000e+07    NaN

       SellerG        Date      Distance      Postcode  ...      Bathroom  \
count    34857       34857  34856.000000  34856.000000  ...  26631.000000
unique     388          78           NaN           NaN  ...           NaN
top     Jellis  28/10/2017           NaN           NaN  ...           NaN
freq      3359        1119           NaN           NaN  ...           NaN
mean       NaN         NaN     11.184929   3116.062859  ...      1.624798
std        NaN         NaN      6.788892    109.023903  ...      0.724212
min        NaN         NaN      0.000000   3000.000000  ...      0.000000
25%        NaN         NaN      6.400000   3051.000000  ...      1.000000
50%        NaN         NaN     10.300000   3103.000000  ...      2.000000
75%        NaN         NaN     14.000000   3156.000000  ...      2.000000
max        NaN         NaN     48.100000   3978.000000  ...     12.000000

                 Car       Landsize  BuildingArea     YearBuilt  \
count   26129.000000   23047.000000   13742.00000  15551.000000
unique           NaN            NaN           NaN           NaN
top              NaN            NaN           NaN           NaN
freq             NaN            NaN           NaN           NaN
mean        1.728845     593.598993     160.25640   1965.289885
std         1.010771    3398.841946     401.26706     37.328178
min         0.000000       0.000000       0.00000   1196.000000
25%         1.000000     224.000000     102.00000   1940.000000
50%         2.000000     521.000000     136.00000   1970.000000
75%         2.000000     670.000000     188.00000   2000.000000
max        26.000000  433014.000000   44515.00000   2106.000000

                    CouncilArea     Lattitude    Longtitude  \
count                     34854  26881.000000  26881.000000
unique                       33           NaN           NaN
top     Boroondara City Council           NaN           NaN
freq                       3675           NaN           NaN
mean                        NaN    -37.810634    145.001851
std                         NaN      0.090279      0.120169
min                         NaN    -38.190430    144.423790
25%                         NaN    -37.862950    144.933500
50%                         NaN    -37.807600    145.007800
75%                         NaN    -37.754100    145.071900
max                         NaN    -37.390200    145.526350

                   Regionname Propertycount
count                   34854  34854.000000
unique                      8           NaN
top     Southern Metropolitan           NaN
freq                    11836           NaN
mean                      NaN   7572.888306
std                       NaN   4428.090313
min                       NaN     83.000000
25%                       NaN   4385.000000
50%                       NaN   6763.000000
75%                       NaN  10412.000000
max                       NaN  21650.000000

[11 rows x 21 columns]

In [16]:
data.drop(columns=[
    'Address', 'Date', 'Postcode',
    'YearBuilt', 'Lattitude', 'Longtitude'
], inplace=True)

In [17]:
data.isnull().sum()

Suburb               0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Distance             1
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
CouncilArea          3
Regionname           3
Propertycount        3
dtype: int64

In [18]:
cols_zero = ['Propertycount', 'Distance', 'Bedroom2', 'Bathroom', 'Car']
data[cols_zero] = data[cols_zero].fillna(0)

In [20]:
data['Landsize'] = data['Landsize'].fillna(data['Landsize'].mean())
data['BuildingArea'] = data['BuildingArea'].fillna(data['BuildingArea'].mean())

In [22]:
print(data['Method'].unique())

['SS' 'S' 'VB' 'SP' 'PI' 'SN' 'W' 'PN' 'SA']

In [24]:
data = pd.get_dummies(data, drop_first=True)

In [36]:
from sklearn.model_selection import train_test_split

In [40]:
data = data.dropna(subset=['Price'])
X = data.drop('Price', axis=1)
y = data['Price']

In [41]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [42]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso

In [43]:
lr = LinearRegression()
lr.fit(X_train, y_train)

yp = lr.predict(X_test)

In [44]:
train_score = lr.score(X_train, y_train)
test_score = lr.score(X_test, y_test)

print("Train R2:", train_score)
print("Test R2:", test_score)

Train R2: 0.6848643213359215
Test R2: 0.6533666160273461

In [45]:
ridge = Ridge(alpha=1.0)
ridge.fit(X_train, y_train)

lasso = Lasso(alpha=0.1)
lasso.fit(X_train, y_train)

C:\Users\Ravi\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.400e+15, tolerance: 8.882e+11
  model = cd_fast.enet_coordinate_descent(

Lasso(alpha=0.1)

In [46]:
print("Intercept:", lr.intercept_)
print("Slopes:", lr.coef_)

Intercept: 668678.8049431199
Slopes: [ 2.63925573e+05 -4.63978213e+04 -8.51983899e+04  1.30454814e+05
  4.18859355e+04  8.56573587e+00  3.62301716e+01  6.58825935e+00
  2.39495623e+05 -5.48762738e+04 -6.67232498e+04  2.68545044e+05
  1.07751176e+05  2.20734678e+05  1.72690800e+05 -1.14847672e+05
 -1.47263823e+05 -5.84067674e+04  5.12614083e+04 -1.28875685e+05
 -2.39529529e+05 -2.05317772e+04  5.45514825e+04 -2.35041134e+05
 -7.32640972e+04 -2.42702683e+05 -9.47649824e-07  1.71169613e+05
 -1.13737654e+05  3.45257527e+03 -2.05596736e+05  8.86089246e+04
  6.16797348e+04  1.81491264e+05  2.27709272e+04  1.92240827e+05
 -7.41769327e-07 -2.07288139e+05  8.52283775e+04 -4.16337030e+04
 -3.24071949e+04  2.22798350e+05  1.69877650e+05 -8.36834861e+04
 -7.28160235e+04  2.17342468e+05  1.49078688e+05 -6.21657819e-07
  2.02971624e+05 -6.43283192e+03 -1.03308599e+04  2.99701194e+05
 -1.14534152e+05 -6.92598901e+04 -1.06008134e+05  1.08111747e+05
  1.45203750e+04  2.21755856e+04 -2.38853936e+04  2.49996560e+05
 -1.82017783e+05 -6.02454510e+04 -1.73244337e+05  7.89445748e+04
 -1.72579951e+05 -1.99462631e+05 -8.72399794e+04 -2.45521372e+04
 -1.07013527e+05 -1.65169071e+05 -1.09997806e+05  3.07907182e+05
  3.51419207e+04  3.48517257e+05  1.61602903e+03 -1.85497193e+05
  4.10263697e+05 -9.29062196e+04 -2.20373731e+05 -1.63875546e+04
 -7.35072302e+03  1.29437125e+04 -7.46760317e+04  3.13128565e+05
 -6.22198209e+04 -2.36965880e+05 -1.22294415e+05 -3.83297873e+05
  5.98528961e+03 -2.25191486e+05  1.53929358e+05  3.33795710e+05
 -1.27506938e+05 -2.20228070e+05  5.32018021e-07  1.52825916e+04
 -8.19164498e+04 -7.65753353e+04  3.97842363e+04  5.74446614e+04
 -4.72497927e+04  3.67340259e+04  2.04199036e+04  3.62642542e+04
 -7.49426472e+04 -3.35596240e+03  1.11730309e+05 -2.71536536e+05
  1.01677995e+05 -5.75977435e+04  3.29171900e+04  7.87680989e+04
 -6.99935594e+04  7.30668308e+03 -1.55773065e+05 -2.23511451e+05
  2.53783730e+05 -1.70752306e+05 -2.90964807e+05 -1.08391577e+04
  5.19706545e+03  1.11245678e+05 -3.13772404e+05 -1.71471320e+05
  4.00007381e+05  3.13903629e+05  2.72722007e+05  7.13048599e+04
  5.05202523e+04 -9.42472402e+04  2.96712748e+04 -1.76652115e+05
 -2.62113868e+05 -5.05642953e+04  9.18776951e+04  9.92016369e+04
 -1.33175042e+04 -2.26686079e+05  6.63334504e-07  1.67233795e+05
 -6.99899560e+04 -9.42189983e+05  1.64216315e+05  3.32190776e+04
  2.39234006e+05  2.54658745e+05 -8.65449851e+04  5.18464513e+04
 -7.70954865e+04  1.65623277e+05 -5.94365258e+04  3.71279470e+05
 -1.43752612e+05  2.10141326e+05  1.00951660e+05 -2.35845569e+05
 -1.92509948e+04 -3.11764683e+05  3.34761587e+05 -8.28460583e+04
 -1.62006459e+05  3.68381603e+04  5.16110001e+04 -5.42419002e-07
 -1.25049304e+05  2.30484082e+05  1.72088303e+05 -2.03302315e+05
 -8.67626886e+03 -5.47269484e+05 -3.21562254e+05  5.04759585e+05
 -1.07256231e+05  7.62047193e+04 -3.73102574e+04 -2.41296670e+05
 -3.37240645e+05 -1.06053927e+05 -1.70864877e+04 -5.96977770e-07
 -3.24117994e+04  5.93735461e+04 -1.57124184e+05 -6.61449649e+04
  8.22177565e+04  5.55406895e+05 -1.10094635e+05  2.57765485e+05
 -1.47736913e+05  1.81596246e+05 -3.47803924e+04  6.68155762e+04
  1.38239244e+05 -2.77600479e+04 -6.74650301e+04 -2.96297918e+05
 -3.35965562e+05  5.30075980e+04  1.00011155e+05 -1.02948089e+05
 -2.82328614e+04  1.91618245e+05  3.48977254e+04  1.48002549e+04
 -4.66981574e+04 -9.40703782e+04  9.13059378e+04 -7.26965793e+03
 -1.58053172e+05  4.37141609e+04  1.48608084e+05  8.13080023e+04
  6.98207820e+04  3.36039200e+04  4.30908776e+05 -4.29295882e+04
  9.91359862e+04  2.35829336e+05 -7.37779599e+04 -4.34829345e+03
  6.35427356e+04  7.36180389e+04 -5.82276603e+04  8.80153804e+04
  2.45505362e-07  1.11908657e+05 -3.33681207e+04  4.84477688e+05
 -9.99234365e+04  1.13585323e+05  2.22016859e+04 -2.99284177e+04
  1.30598333e+04  8.41100700e-07  5.13112010e+04 -1.64191724e+05
 -1.88389221e+05  1.42773758e+05  8.39961022e+03  2.19805695e+05
 -5.03664170e+04  1.12278936e+04  9.06185854e+04 -2.11355935e+05
 -4.36096962e+04  1.20672536e+05 -5.70925143e+03 -3.99583614e+04
  5.59770651e+05  1.54631754e+05  7.49992340e+04  1.56576080e+04
  8.25388745e+04 -3.20896296e+04 -5.21395620e+04 -3.61811905e+05
  9.04466828e+04 -4.83822078e-07  1.36283964e+05  2.02477561e+05
  2.07591466e+05  3.30889112e+05 -3.83839197e+04  2.03666820e+05
  4.76931746e-07  2.68809642e+05 -1.89908144e+05 -6.72934952e+04
 -3.07579872e+05 -9.75470637e+04  4.73835093e+05  2.29893067e+05
 -1.38475008e+05 -7.83138809e+03  4.08546223e+05  6.12741931e+04
  7.16533495e+04 -6.85289227e+04 -5.59742383e+04  2.82928327e+05
 -1.24787186e+05 -2.88517271e+05 -7.65525749e+04 -1.63219867e+05
  1.93092986e+05  1.24102067e+05 -8.77991813e+04  1.40209204e+05
  6.30718831e+04  1.47396148e+05 -9.64267718e+03 -7.46603756e+04
 -7.16354271e+04 -2.15925892e+05 -8.69781355e+04 -1.14383455e+05
 -4.01230724e+05 -5.79659404e+04 -5.96905080e+04 -3.48642402e+04
  6.10575585e+03 -2.39454625e+05 -1.82997214e+05  5.36673363e+04
 -1.85168803e+05  4.48515943e+05  7.95145833e+04 -4.61857008e+04
 -1.28671700e+05 -1.75944018e+05  6.08622451e+04 -5.76221332e+04
 -7.31049798e+04 -6.46217350e+04  3.76367219e+03  1.17809947e+05
 -1.72149158e+05  2.93311507e+05 -4.38910884e+04  5.93959307e+04
  1.25430811e+05  9.02761447e+03  3.85996698e+04  9.16861365e+04
  2.56226138e+04 -2.72748278e+04 -4.20249431e+04 -2.56299115e+05
  1.88366263e+05  3.73402145e-07 -2.90761971e+05 -2.11463045e+05
  3.03396880e+05 -2.02665794e+05  1.68351523e+04  7.17362680e+04
 -9.00486247e+04 -2.12397192e+05 -1.97925971e+05 -1.24559634e+05
  3.84241617e+04  5.14860104e+04 -5.23369925e+04 -1.56335925e+05
  1.42901340e+05 -4.97617293e-07  3.23956240e+04  2.52633614e+05
 -3.63478306e+04 -1.25318025e+05  1.62117629e+05  6.10658706e+04
  3.91534882e+05 -1.19943565e+05 -1.43290146e+04  1.45415892e+05
 -2.06422013e+04  3.58832909e+04 -2.71636531e+05 -4.77413845e+05
  6.87781721e-07  7.31144935e+04  6.10953849e+04  1.34517904e-07
  3.97424032e+04 -4.05081664e-07  7.59691903e+03  1.39494659e-06
  1.20606273e-07 -8.87769112e+04  1.00106469e+05  5.78332404e+05
  2.41979985e+05 -2.89013513e+05  3.73169314e-07  9.02371593e+04
 -9.43142372e+04 -1.76799625e+05  6.63201258e+04 -2.19445170e+05
  1.58151009e+05  1.46764800e+05 -1.07951216e+05  9.70121069e+03
 -4.80271950e+04  5.26600127e+05  1.32875257e+05  1.58251141e+03
  3.15913443e+05  1.43027697e+05  5.00072075e+04  3.71369609e+05
 -4.29126187e+04 -1.35233069e+04 -5.59694704e+04  5.70323738e+04
  2.04167202e+05  1.24819529e+05 -2.60080412e+05 -6.00274683e+04
  5.45396920e+04  1.58412898e+05  7.72076870e+04  8.08258322e+05
  8.90246394e+04 -7.63493604e+04  9.22964219e+04 -2.41186208e+05
 -5.29648576e+04  4.71013267e+04 -1.76308095e-06  9.22170632e+04
  6.80040414e+04  5.50828779e+04  1.32795917e+05 -1.80000785e+05
 -4.92589565e+04  6.20032131e+04 -3.13054848e+04  3.11802903e+05
  3.40652344e+05 -1.44713194e+05  5.26017403e+04 -1.49325011e+05
  5.22889103e+05  9.55180534e+04  6.81029633e-09  1.69999792e+05
  1.74683684e+05  5.99653864e+05  9.47062802e+04 -2.55580248e+05
 -6.63655640e+03 -3.04208838e+05  4.95978946e+04 -3.77862910e+05
  4.58268035e+04 -9.38330783e+04 -6.92962203e-08  2.36086279e+05
 -2.61145121e+04  1.87022074e+05  1.33790309e-07  2.52848110e+05
  6.28075574e+04  3.10815729e+05 -6.06463846e+04 -1.02096237e-07
 -1.42463250e-08 -4.77074475e+04 -4.75195458e+04  6.97791348e+04
  4.62059781e+04 -2.01648091e+05  1.90504539e+06  1.43037803e+05
 -2.12564876e+05  4.40311839e+04 -3.52103335e+04 -5.74844393e+05
 -1.71271625e+05 -6.29810875e+04 -1.18397320e+05  2.68975775e+04
  5.79590079e+04  3.38304444e+05  1.27474777e-08  1.67233315e+04
  7.29646804e+04  8.35020454e+04  1.26587102e+05  1.62231471e+05
  4.80223472e+04 -1.61270845e+05 -7.82931606e+04 -2.06986442e-07
  1.59546057e+06  1.99652277e-08  4.84494328e+04  8.75424657e+04
 -1.10994602e+04  6.30423698e+04 -2.02581148e+04 -2.66308289e+05
 -1.83593454e+05  7.24275071e+03 -4.66824021e+05 -1.61673115e+05
 -2.00248905e-07  1.05646905e-07  7.75395376e+04  1.32870590e+05
  6.09100402e+04  5.36396957e+05  2.46383445e+04  8.97562752e+05
 -5.35051720e+04 -2.21249309e+05  4.60476340e+04  1.84169039e-07
 -8.61783576e+04 -4.88536826e+04 -7.16287074e+04 -6.61821105e-08
  1.44829888e+04  3.32872788e+04  6.19263804e+04 -1.98094290e+05
  5.95717066e+05  1.35102859e+05  1.10756550e+05  1.16238037e+05
  2.54174782e+04 -1.49742846e-07 -3.35377449e+03 -5.71252358e+04
  8.03516059e+04  1.21616727e+05  3.05966176e+04  9.16611092e+04
  9.84482233e+04  2.06055120e-08  1.32414696e+05  2.59028363e+04
  8.67642497e+04  2.07510311e-08 -1.89063609e+05 -2.18108510e+05
  1.05532221e+05  4.01067331e+05 -1.20198820e-07 -3.42841436e+05
  4.93990210e+05  2.11715945e+05  2.56768193e+05  3.64248671e+05
 -5.24676681e+04  4.01341822e-08  7.79560074e+04 -8.53051434e+04
  3.86177358e+04 -7.43365981e+04  4.91426001e+05  4.34301910e-08
 -2.33959753e+05  1.42419061e+05 -3.01184277e+04 -7.15193960e+04
  1.40770722e+05 -2.26484074e+04 -4.44757404e+04  3.22456615e+05
  7.08527791e+04  2.81509297e+05 -5.64659322e+05 -2.42438942e+03
  1.00889942e+05 -4.85678128e+04  5.99372425e+04  9.58098099e-08
 -4.42543761e+04 -1.92490056e+05  4.95565473e-08 -1.80479527e+04
 -1.03027560e-08  3.67853524e+05 -7.44475983e-08 -1.33822064e+05
  5.35500270e+04  2.64742771e+05  1.53250360e+05 -4.69784003e+04
  8.14612894e+04 -2.29920261e-08 -2.16726598e+05 -5.91220835e+04
  7.55145266e+03  1.32119991e+05  4.16357899e+04 -9.17590497e+04
  1.40627153e+05  1.11596564e+05  4.96511348e-08 -9.09077494e+04
  1.28695072e+05  2.73968982e+04  7.57136149e-08  2.06258879e+05
  8.41035266e+04 -1.81033274e+05  6.73824535e+04  3.98472472e+04
  1.20128852e+05 -1.98223135e+05  5.49713993e+04 -2.60029997e+04
  9.19452847e+04  8.60048118e+05  1.60352494e+05 -5.25709418e+04
  1.93360710e+05  8.29565352e+03 -1.11904228e-08  5.11441357e+04
 -1.93547449e+05  1.05221852e+05  3.44330236e+05  6.55356141e+04
 -2.83856571e+04  6.64347024e+04  1.43465875e+04 -2.65281083e+04
 -2.82169584e+05  1.25457240e+05 -1.06576335e+04  3.70825900e+04
 -1.68074621e-09  2.09947262e+04  7.56135484e+04  3.19022134e+05
  2.30985626e+05  2.51457095e-08  3.18624164e+05 -1.41444616e-08
  4.12359664e+05 -2.50430572e+04  7.96390074e+04  4.82109282e+04
  7.84957181e+04 -1.07576834e+05  1.95629104e+05  6.07194733e+04
 -6.41471424e+04  2.00947118e+05 -5.85005916e+05 -3.84630325e+05
 -2.80969752e+04  3.27127054e-08  3.97849362e-08  1.66648928e+04
  5.88352137e+04  9.15204436e+03  2.50023448e+05  3.97151662e+04
  3.24689622e+04 -1.69804703e+05  4.83006980e+03 -3.78058758e-08
 -8.58977593e+04 -5.08531334e+05  3.49975259e+05  2.30831839e+05
  4.03150822e+04  1.01802142e+05  5.19426479e+04  2.09869509e+04
  5.01086900e+04 -1.30622804e+04 -3.87239450e+04  2.30330377e+05
 -2.07158403e+05  3.68303892e+05 -3.82944478e+05  2.01742842e+05
 -2.16532499e-08 -1.73693024e-08  1.39525755e+05  8.07642964e+04
 -5.61517227e+05  1.38026842e+05 -3.86114020e+05 -2.25740554e+04
 -6.07276845e+04 -2.79803432e+05 -1.30967237e-09 -8.46284820e-10
  2.09406491e+04  3.66708264e-09  1.18990229e+06  5.81161676e+04
  1.51733782e+05 -4.80213203e-09 -3.99942367e+04  6.94399205e-10
  1.39698386e-09  3.37865791e+04 -2.88597114e+05  1.74622983e-10
  5.71804355e+04 -5.36739882e+04  1.08172198e+05  5.46826350e+05
 -1.56927301e+05 -1.74622983e-10  7.92453348e+04 -1.55915197e+05
 -8.75997200e+04 -4.87124139e+05 -6.88769104e+04  1.36950054e+05
  1.30720215e+05 -1.44051990e+05  4.02006891e+04  2.91294222e+05
  2.48584130e+05 -1.99389455e+04  7.72894010e+05 -1.50666884e+05
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -2.78307866e+05
  9.69191055e+04 -7.71927838e+04  6.24524072e+05  1.30162853e+05
  4.43442985e+04  0.00000000e+00  0.00000000e+00  0.00000000e+00
  9.30905419e+05  2.21700351e+05 -1.34841831e+05 -8.60318519e+04
  2.76644463e+05  1.32781547e+04  7.64417400e+04  1.02645690e+05
  6.81537419e+04 -2.65863802e+04  5.76309266e+03  3.31621546e+04
 -1.62947582e+04 -3.03902725e+05  5.67403429e+04  1.52467023e+04
  1.10834094e+05  1.20225249e+03  1.60664735e+05  2.32626770e+05
 -8.19875213e+04  0.00000000e+00  0.00000000e+00 -8.74521657e+04
  0.00000000e+00  6.32712158e+05  1.06740430e+05  2.42381391e+05
  4.59410821e+04  0.00000000e+00  0.00000000e+00  0.00000000e+00
  1.69226114e+05 -1.01294731e+05  0.00000000e+00  4.19065387e+05
  5.20419700e+05 -1.79711841e+05  3.20534320e+05  1.88864863e+05
 -9.99378397e+03  3.78194901e+05  1.05684854e+05 -3.17614988e+03
 -7.83429328e+04 -7.28432043e+04  2.17128316e+05  1.44780942e+05
  4.48037824e+05  1.80838028e+05 -2.48083777e+05  1.89936283e+05
  7.74877740e+03 -1.14080292e+05  1.88366263e+05  6.44218469e+04
  4.03126936e+04  2.04086803e+05 -5.82775555e+04 -2.61622940e+04
  8.87409831e+04  2.71891791e+05  1.86262520e+05  4.15002915e+04
 -1.78497175e+05 -1.82018906e+04  1.05257744e+05  3.29685292e+05
 -1.38381746e+05  3.48984167e+05  2.04019407e+05  1.08238544e+05
 -1.30185942e+05  2.35239443e+05]

In [ ]:
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("Mean Absolute Error:", mae)
print("Root Mean Squared Error:", rmse)
print("R2 Score:", r2)